### ISSUE TITLE
User Story 29 & User Story 30

### ISSUE THREAD

**Issue by KieraAllen** [Arique1104/monster_shop_2005#30]
(2 stories on this Issue to match Issue numbers and User Story numbers)

User Story 29, User views an Order Show Page

As a registered user
When I visit my Profile Orders page
And I click on a link for order's show page
My URL route is now something like "/profile/orders/15"
I see all information about the order, including the following information:
- the ID of the order
- the date the order was made
- the date the order was last updated
- the current status of the order
- each item I ordered, including name, description, thumbnail, quantity, price and subtotal
- the total quantity of items in the whole order
- the grand total of all items for that order

User Story 30, User cancels an order

As a registered user
When I visit an order's show page
I see a button or link to cancel the order
When I click the cancel button for an order, the following happens:
- Each row in the "order items" table is given a status of "unfulfilled"
- The order itself is given a status of "cancelled"
- Any item quantities in the order that were previously fulfilled have their quantities returned to their respective merchant's inventory for that item.
- I am returned to my profile page
- I see a flash message telling me the order is now cancelled
- And I see that this order now has an updated status of "cancelled"

**Comment by Arique1104** [comment]
Hey Team...I'm a bit stuck on how to add a column to the ItemOrder joins table.
My user story wants me to add the following:
Each row in the "order items" table is given a status of "unfulfilled"
The order itself is given a status of "cancelled"
This looks like adding a column called current status, but it seems that there are two different columns and I'm not sure what all they are tracking.
But based off of the user story instructions, it is the following:
orders
Is going to get a Current Status that is independent of order item status
There are three things that are official that this column needs some logic around: order pending, order shipped, order cancelled.
order_item
Is going to get a Current Status that means unfulfilled
But the thing that is getting to me is that I don't actually know what it is we want to track and what each of these pieces means as far as giving them logic or deciding where and how they need to live.
At first, I think about adding the column straight into order items  joins table, like it says.  But is it a number, like in roles?  Is it a string like the rest of it's attributes?  I am confused about that piece.  Any advice is welcomed.

From what you said it sounds like you should add a column to item_orders and I think the best option would be for it to be an integer tied to an enum - just like we did with roles.
